// GlassOS icon: renders qml/icons/<name>.svg crisply at the current device pixel ratio.
// Icons are generated by tools/make_icons.py (one consistent style for the whole OS).
import QtQuick

Image {
    property string name: ""
    property real size: 16

    width: size
    height: size
    source: name !== "" ? Qt.resolvedUrl("../icons/" + name + ".svg") : ""
    sourceSize.width: Math.ceil(size * Screen.devicePixelRatio)
    sourceSize.height: Math.ceil(size * Screen.devicePixelRatio)
    fillMode: Image.PreserveAspectFit
    smooth: true
    cache: true
}
